Be kristina
serge-auro/easy-habit pull request #12
Opened 2024-04-24 20:30 UTC by Buddyroo

2024-04-24 21:28 UTC, serge-auro requested changes

2024-04-24 21:28 UTC, serge-auro commented on actions.py
> +    cur.execute("INSERT INTO users (id, creation_date) VALUES (?, ?)",
у нас нет такой таблицы, у нас только
https://github.com/serge-auro/easy-habit/blob/817fd200307ba50f7765614c6fbe359d0c5f4947/DB_structure.py#L12

2024-04-24 21:28 UTC, serge-auro commented on actions.py
> +def assign_habit(user_id, habit_id, frequency_name, frequency_count):
пропиши, чтобы тип ожидался определённый 
frequency_name: FREQUENCY

2024-04-24 21:28 UTC, serge-auro commented on actions.py
> +def edit_habit(user_id, habit_id, frequency_name, frequency_count):
пропиши, чтобы тип ожидался определённый
frequency_name: FREQUENCY

2024-04-24 21:28 UTC, serge-auro commented on methods_test.py
> +    cur.execute("INSERT INTO users (id, creation_date) VALUES (?, ?)",
название таблицы user (без S)

2024-04-24 21:28 UTC, serge-auro commented on DB_add_info.py
этот файл лучше удалить, тк будет использоваться 
https://github.com/serge-auro/easy-habit/blob/BD_SQL/new%20add%20data2.py
лучше использовать только его и работать с данными оттуда.

2024-04-25 01:00 UTC, Buddyroo commented on actions.py
> +    cur.execute("INSERT INTO users (id, creation_date) VALUES (?, ?)",
надо, кстати, тогда исправить 
            48 строка FOREIGN KEY (user_id) REFERENCES users(id),
35 FOREIGN KEY (user_id) REFERENCES users(id),

2024-04-25 09:13 UTC, serge-auro approved these changes

2024-04-25 09:14 UTC, merged